### ISSUE TITLE
SDK: Issue related to "Kuzzle/addListener" section

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/sdk-documentation#114]
Hi,

is this example stale ? 

```javascript
  var listenerId = kuzzle.addListener('connected', function (room, subscription) {
    // Actions to perform when receiving a 'subscribed' global event
  });
```

And can you confirm me that all events in the list of "special events" specify the arguments passed to the addListener callback ?

Best regards

**Comment by dbengsch** [comment]
Issue moved to [kuzzleio/documentation #42](https://github.com/kuzzleio/documentation/issues/42) via [**ZenHub**](https://www.zenhub.com/)
