### ISSUE TITLE
Issue related to "Kuzzle/dataCollectionFactory" section

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/sdk-documentation#51]
Hello people,

I'm working on the definition file for typescript for the JS SDK,

I'm trying to do things like that : 

`dataCollectionFactory(index?:string, collection:string):KuzzleDataCollection;`

The compiler returns me that required parameters must be first, and a required parameter cannot follow a optional parameter.

According to https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3922-parameter-list.

Can we please, imagine a refactoring process to match these spec in order to a future support of typescript.

Best regards

Thanks.

**Comment by scottinet** [comment]
We might invert these two arguments for the `dataCollectionFactory` method, it won't do much harm.

But you'll encounter the exact same problem with the majority of methods taking a required callback, with optional arguments, for instance [fetchDocument](http://kuzzle.io/sdk-documentation/#fetchdocument).
And for these methods, my personal feeling is that the callback should always be the last argument. This is to keep the code readable by avoiding things like this:
```js
kuzzle
  .dataCollectionFactory('collection')
  .fetchDocument('some document id', function (err, res) {
    /*
     * code
     * handling
     * the 
     * retrieved
     * document
     * can
     * be
     * quite
     * long
     */
  }, {queuable: false});
```

Moreover, this limitation seems strictly limited to Typescript. The Ecmascript 6 standard allows defining required parameters after defaulted ones.

**Comment by PierreCavalet** [comment]
What about passing a "params" parameter which would be an object containing both optional and required parameters, and the callback as the second and last parameter ?

It would look like this : 
```
kuzzle
  .dataCollectionFactory('collection')
  .fetchDocument({documentid: 'some document id', queuable: false}, function (err, res) {
    /*
     * code
     * handling
     * the 
     * retrieved
     * document
     * can
     * be
     * quite
     * long
     */
  });
```

see this thread : http://stackoverflow.com/questions/5135566/javascript-callbacks-and-optional-params

**Comment by ScreamZ** [comment]
Yeah, I thing it's the good way and it looks like jQuery.ajax method

**Comment by scottinet** [comment]
@PierreCavalet : I have two arguments against your proposal:

- more complicated methods like `advancedSearch` will look unreadable with your solution
- our SDK specifications are language-agnostic, and in some languages, implementing this can be painful

Just so you know, there is an intense debate going on in our desk about the matter of optional arguments that aren't after required ones.

The current state of the question is:

- the sole argument for the current model is that it improves code readability
- this is also the sole argument against it: optional parameters in the last positions improve documentation readability
- I can't find any convention against our model, but I can't find one either supporting this
- there isn't any problem with any language we know mainly thanks to method overloading. Even in C this won't be a problem using variadic macros

So, we are kinda in a grey area here. Either we keep the current model, that doesn't cause any real problem, or we refactor it, meaning we are due for a heavy refactor in NodeJS/JS, Android, Swift and Objective C, for a very small gain.

We're still discussing this matter internally.

**Comment by scottinet** [comment]
One last matter to consider: there are a lots of methods in the SDK that look very similar.
The general rule of thumb is that "send" methods take an optional callback, while "read" methods take a required callback.
If we refactor the read method to move the required callback before the optional parameter, we break the homogeneity of the SDK: some methods will be "callback last", and some won't.
Homogeneity is very important to keep the SDK predictable, thus improving its usability.

**Comment by scottinet** [comment]
To summarize, there are two distinct cases:

- methods with optional arguments and required callbacks
- methods with optional arguments and no callback

Like I said, the former kind of methods are still under discussion.

The latter kind of methods will be refactored so that optional arguments will be after the the required ones. Thus far, `dataCollectionFactory` seems to be the only method we need to refactor. I'll write an issue on each SDK repository to change refactor this method.

**Comment by scottinet** [comment]
Hi,

The `dataCollectionFactory` method and its documentation has been modified on the `develop` branch. This will be merged on the `master` on Wednesday 1st, June

**Comment by ScreamZ** [comment]
Thanks
