### ISSUE TITLE
SDK: Missing createIndex implementation

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/sdk-documentation#74]
We have forget to create a `createIndex` method in all SDK
- SDK JS
- SDK Android
- SDK iOS (swift & objective c)
- SDK PHP

**Comment by dbengsch** [comment]
Issue moved to [kuzzleio/documentation #37](https://github.com/kuzzleio/documentation/issues/37) via [**ZenHub**](https://www.zenhub.com/)
